language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-sms.gemspec
- gem install sensu-plugins-sms-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: emNzdvl4s3VWDxC899GhnMp/dXuyPbw4mrRBck079tZMy/TXkcEzjBxMeqg/TxRNUD4JGIgY2vShZoqD5olOUykWUjGu65L5Tr84TqxtkrEnyyc+lkVREZNapxaJy5D3umHcSxUrzMY7ARR8d0u9KIgrjAhle8/QAjRHXKAG9DE=
  gem: sensu-plugins-sms
  on:
    tags: true
    all_branches: true
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-sms
